apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: jeetdocker21/test:26
        ports:
        - containerPort: 5000
